### PR TITLE
#20: Feed language correction/simplification

### PR DESCRIPTION
**Pull request by lat9**
Correction for #20.

### CODE REVIEW

**Comment by lat9** [comment]
@torvista, for whatever reason I can't add you as a requested reviewer.  Please review these changes since I don't have a multi-language installation on which to validate.

**Comment by torvista** [comment]
The language generation is correct but the feeds generated are missing the _en/_es suffixes.

**Comment by lat9** [comment]
Thanks for the quick response, @torvista; let me get that corrected ..

**Comment by lat9** [comment]
@torvista, let me know whether that correction fixes the missing language-suffix issue.

**Comment by torvista** [comment]
yes, works for me.

**Pull request merged**
